config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts
  resources :relationships
  root 'pages#index'

  get '/home' => 'pages#home'
  get '/user/:id' => 'pages#profile'
  get '/explore' => 'pages#explore'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) } # newest tweets / posts first
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  #helper methods

  def follow(other)
    active_relationships.create(followed_id: other.id)
  end

  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end

  def following?(other)
    following.include?(other)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  end

  def home
    following = Array.new
    for @f in current_user.following do
      following.push(@f.id)
    end

    @posts = Post.where("user_id IN (?)", following)
    @newPost = Post.new
  end

  def profile
    if (User.find_by_username(params[:id]))
      @username = params[:id]
    else 
      redirect_to root_path, notice: "User not found!"
    end

    @posts = Post.all.where("user_id = ?", User.find_by_username(params[:id]).id)
    @newPost = Post.new
    @toFollow = User.all.last(5)
  end

  def explore
    @posts = Post.all
    @newPost = Post.new
    @toFollow = User.all.last(5)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |f|
      if @post.save
        f.html { redirect_to "", notice: "Post created!" }
      else
        f.html { redirect_to "", notice: "Post not saved." }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :content)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to(:back)
  end
    
  def destroy
    user = Relationship.find(params[:id]).followed 
    current_user.unfollow(user)
    redirect_to(:back)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rwitter</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/"><img class="navbar-brand" src="/assets/bull.png"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><%= link_to "Explore", explore_path %></li>
            <% if user_signed_in? %>
            <li><%= link_to "Notifications", home_path %></li>
            <li><%= link_to "Messages", home_path %></li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li>
              <form class="navbar-form navbar-right">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search rwitter">
                </div>
              </form>
            </li>
            <% end %>
            <li class="dropdown">
              <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="/assets/penguin.png" class="rounded-img"><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <li><a href="/user/<%= current_user.username %>">Profile</a></li>
                  <li><%= link_to "Account", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to "Sign Up", new_user_registration_path %></li>
                  <li><%= link_to "Sign In", new_user_session_path %></li>
                <% end %>
              </ul>
            </li>
          </ul>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <% if params[:id] != nil %>
      <% @url = '/user/' + params[:id] %>
      <% if current_page?(@url) %>
      <section class="profile-banner">
      </section>
      <div class="row">
        <div class="col-sm-12" style="background-color: white;">
          <div class="container">
            <div class="col-sm-3">&nbsp;</div>
            <div class="col-sm-6" style="margin-top: 5px">
              <div class="col-sm-2" style="font-size: 100%; opacity: 0.7;">POSTS<br>
                <h6 style="color: #0084B4; font-size: 150%;"><%= User.find_by_username(params[:id]).posts.count %></h6>
              </div>
              <div class="col-sm-2" style="font-size: 100%; opacity: 0.7;">FOLLOWERS<br>
                <h6 style="color: #0084B4; font-size: 150%;"><%= User.find_by_username(params[:id]).followers.count %></h6>
              </div>
              <% if user_signed_in? %>
                <div class="col-sm-8" style="text-align: right; margin-top: 5px;"><a href="/users/edit"><li type="button" class="btn btn-default" style="color: grey; opacity: 0.8; font-weight: bold;">EDIT PROFILE</li></a></div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>

    <div class="container">
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% elsif alert %>
        <p class="alert"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/explore.html.erb
<div class="row">
    <div class="col-xs-3">
        
        <div class="panel panel-default">
          <div class="panel-body">
            <h5 style="color: grey; font-size: 125%;">Explore</h5>
            <p style="opacity: 0.5; font-size: 90%;">
              This page aggregates posts from ALL users. This means that you can find new people to follow,
              and your posts will also appear here so other people can see your opinions and interests and follow you
              if they chose.
            </p>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
             <h5 style="color: grey; font-size: 125%;">Trends</h5>
              <a href="">#Trend #1</a><br>
                <span style="color: grey;">31k Posts</span><br><br>
              <a href="">#Trend #2</a><br>
                <span style="color: grey;">25k Posts</span><br><br>
              <a href="">#Trend #3</a><br>
                <span style="color: grey;">16k Posts</span><br><br>
          </div>
        </div>
    </div>
    <div class="col-xs-6">
        <%= render '/components/post_form' %><% if user_signed_in? %> <br> <% end %> <br>
        
        <% @posts.each do |post| %>
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            
            <div class="col-sm-1">
              <img src="/assets/smart-bull.png" class="img-responsive"></img>
            </div>
            <div class="col-sm-11">
              <p class="post-title"><span class="post-owner"><a href="/user/<%= User.find(post.user_id).username %>"><%= User.find(post.user_id).username %></a></span> <span class="post-creation">- <%= post.created_at.to_formatted_s(:short) %></span></p>
              <p class="post-content"><%= post.content %></p>
            </div>
            
            <div class="col-sm-12">
              <p class="post-links">
                <span class="glyphicon glyphicon-comment g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-retweet g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-heart g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-option-horizontal g-links" aria-hidden="true"></span>
                <a href="">View conversation</a>
              </p>
            </div>
            
          </div>
        </div>
        <% end %>
        
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            <div class="col-sm-12">
            <center><img src="/assets/penguin.png" height="25px" width="25px"></img>
              <a href="#top"><p class="opacity: .7;">Back to top <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></p></a></center>
            </div>
          </div>
        </div>
    </div>
    <div class="col-xs-3">
        <div class="panel panel-default">
          <div class="panel-body">
             <h5 style="color: grey; font-size: 125%;">Who to follow</h5>
             <% for @u in @toFollow do %>
               <p style="font-weight: bold; opacity: 0.85;" ><a href="/user/<%= @u.username %>"><%= @u.username %></a></p>
             <% end %>
          </div>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-body">
            <p style="opacity: 0.5; font-size: 90%;">© 2016 Flutter  About  Help  Terms  Privacy  Cookies  Ads Info  Brand  Blog  Status  Apps  Jobs  Advertise  Businesses  Media  Developers</p>
          </div>
        </div>
        
        
    </div>
</div>

app/views/pages/home.html.erb
<div class="row">
    <div class="col-xs-3">
      
        <div class="panel panel-default">
          <div class="panel-image hide-panel-body">  
            <img src="/assets/balloon.jpg" class="panel-image-preview">
          </div>
          <div class="panel-footer">
            <div class="row">
                <div class="col-sm-2"><img src="/assets/smart-bull.png" class="img-responsive"></div>
                <div class="col-sm-10"><h4><%= current_user.username %></h4></div>
                <div class="col-sm-12">
                  <div class="col-sm-6">POSTS<br>
                    <h6><%= current_user.posts.count %></h6>
                  </div>
                  <div class="col-sm-6">FOLLOWERS<br>
                    <h6><% current_user.followers.count %></h6>
                  </div>
                </div>
            </div>

          </div>
        </div>
        
        <div class="panel panel-default">
          <div class="panel-body">
             <h5>Trends</h5>
              <a href="">#Trend #1</a><br>
                <span style="color: grey;">31k Posts</span><br><br>
              <a href="">#Trend #2</a><br>
                <span style="color: grey;">25k Posts</span><br><br>
              <a href="">#Trend #3</a><br>
                <span style="color: grey;">16k Posts</span><br><br>
          </div>
        </div>
    </div>
    <div class="col-xs-6">
        <%= render '/components/post_form' %><br><br>

        <% for @p in @posts %>
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            
            <div class="col-sm-1">
              <img src="/assets/smart-bull.png" class="rounded-img" height="50px" width="50px"></img>
            </div>
            <div class="col-sm-11">
              <p class="post-title"><span class="post-owner"><a href="/user/<%= User.find(@p.user_id).username %>"><%= User.find(@p.user_id).username %></a></span> <span class="post-creation">- <%= @p.created_at.to_formatted_s(:short) %></span></p>
              <p class="post-content"><%= @p.content %></p>
            </div>
            
            <div class="col-sm-12">
              <p class="post-links">
                <span class="glyphicon glyphicon-comment g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-retweet g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-heart g-links" aria-hidden="true"></span>
                <span class="glyphicon glyphicon-option-horizontal g-links" aria-hidden="true"></span>
                <a href="">View conversation</a>
              </p>
            </div>
            
          </div>
        </div>
        <% end %>
        
        <div class="panel panel-default post-panel">
          <div class="panel-body row">
            <div class="col-sm-12">
            <center><img src="/assets/penguin.png">
              <a href="#top"><p>Back to top <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></p></a>
            </center>
            </div>
          </div>
        </div>
    </div>
    <div class="col-xs-3">
        <div class="panel panel-default">
          <div class="panel-body">
            <p class="btm-links">© 2016 Flutter  About  Help  Terms  Privacy  Cookies  Ads Info  Brand  Blog  Status  Apps  Jobs  Advertise  Businesses  Media  Developers</p>
          </div>
        </div>
    </div>
</div>

app/views/pages/index.html.erb
<% if !user_signed_in? %>
    <style>
        body {
          background-image: url('/assets/prague.jpg');
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;
          background-size: cover;
          background-repeat: no-repeat;
          background-position: center center;
          background-attachment: fixed;
          min-height: 100%;
        }
        h1 {
            color: white;
            font-weight: bold;
        }
        .text {
            color: white;
            font-weight: 300;
            font-size: 150%;
        }
        .footer-links {
            text-align: center;
            color: white;
            margin-top: 30%;
            font-size: 90%;
        }
        .user-links {
            margin-top: 5%;
        }
        .user-links a {
          color: #5d4a4a;
        }
        .user-links a:hover {
          text-decoration: none;
        }
        .user-form {
            margin: 5px;
        }
    </style>
    
    <div class="container-index row">
        <div class="col-sm-9 col-sm-offset-3">
            <h1>Welcome to Rwitter.</h1>
            <p class="text">
                Connect with your buddies. Chat with new friends.<br>
                Share your adventures. Have fun! <br>
                Just like a blog, but with less characters!
            </p>
        </div>
        <div class="col-sm-9 col-sm-offset-3 user-links">
          <button class="btn btn-lg btn-default">
            <%= link_to "Log In", new_user_session_path %>
          </button>
          <button class="btn btn-lg btn-default">
            <%= link_to "Sign Up", new_user_registration_path %>
           </button> 
        </div>
        
        <div class="col-sm-12">
            <p class="footer-links">About  Help  Blog  Status  Jobs  Terms  Privacy  Cookies  Ads  info  Brand  Advertise  Businesses  Media  Developers  Directory © 2016 Rwitter</p>
        </div>
        
    </div>

<% else # if the user IS signed in, render the following %>

    <script>document.location = "/home"</script>

<% end %>

app/views/pages/profile.html.erb
<div class="row">
  <div class="col-xs-3">
    <div class="col-sm-12" style="margin-top: -150px;">
      <img src="/assets/smart-bull.png" height="150px" width="150px">
    </div>
    <div class="col-sm-12">
      <h3 style="font-weight: bold;"><%= params[:id] %></h3>
      <p>The rain in Spain... is wet.</p>
    </div>
  </div>
    
  <div class="col-xs-6">
      <%= render '/components/post_form' %><br><br>

      <% @posts.each do |post| %>
      <div class="panel panel-default post-panel">
        <div class="panel-body row">
          
          <div class="col-sm-1">
            <img src="/assets/smart-bull.png" class="img-responsive"></img>
          </div>
          <div class="col-sm-11">
            <p class="post-title"><span class="post-owner"><a href="/user/<%= User.find(post.user_id).username %>"><%= User.find(post.user_id).username %></a></span> <span class="post-creation">- <%= post.created_at.to_formatted_s(:short) %></span></p>
            <p class="post-content"><%= post.content %></p>
          </div>
          
          <div class="col-sm-12">
            <p class="post-links">
              <span class="glyphicon glyphicon-comment g-links" aria-hidden="true"></span>
              <span class="glyphicon glyphicon-retweet g-links" aria-hidden="true"></span>
              <span class="glyphicon glyphicon-heart g-links" aria-hidden="true"></span>
              <span class="glyphicon glyphicon-option-horizontal g-links" aria-hidden="true"></span>
              <a href="">View conversation</a>
            </p>
          </div>
          
        </div>
      </div>
      <% end %>
      
      <div class="panel panel-default post-panel">
        <div class="panel-body row">
          <div class="col-sm-12">
          <center><img src="/assets/penguin.png">
            <a href="#top"><p>Back to top <span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span></p></a>
          </center>
          </div>
        </div>
      </div>
  </div>
  <div class="col-xs-3">
      <%= render '/components/follow_button', :user => User.find_by_username(params[:id]) %>
      <div class="panel panel-default">
        <div class="panel-body">
           <h5 style="color: grey; font-size: 125%;">Who to follow</h5>
           <% for @u in @toFollow do %>
             <p style="font-weight: bold; opacity: 0.85;" ><a href="/user/<%= @u.username %>"><%= @u.username %></a></p>
           <% end %>
        </div>
      </div>
      
      <div class="panel panel-default">
        <div class="panel-body">
           <h5 style="color: grey; font-size: 125%;">Trends</h5>
            <a href="">#Trend #1</a><br>
              <span style="color: grey;">31k Posts</span><br><br>
            <a href="">#Trend #2</a><br>
              <span style="color: grey;">25k Posts</span><br><br>
            <a href="">#Trend #3</a><br>
              <span style="color: grey;">16k Posts</span><br><br>
        </div>
      </div>
  </div>
  
</div>